### PR TITLE
Use the PublicationRepository to fix the TransactionTooLargeException

### LINKED ISSUE #286: Publication might be too big to be sent through an Intent to the Navigator
`Intent` extra data is limited in size, but `Publication` is not. This can produce a `TransactionTooLargeException` for big publications when starting the Navigator's `Activity`.

The PR https://github.com/readium/r2-testapp-kotlin/pull/285 attempts to fix this problem with a global variable in the Navigator, but this strategy has some issues described in the PR's comments.

Possible alternatives are raised in https://github.com/readium/r2-testapp-kotlin/pull/285#issuecomment-577283869.

### PR DESCRIPTION
**Pull request by mickael-menu**
Fixes #286 

I decided to throw an Exception (and close the Activity in release mode) if an app still uses the old `publication` intent extra. Since apps can crash when loading a big publication, better make sure they are actually upgrading to this new method as soon as possible.

Usage:

```kotlin
// In the source Activity, do:
intent.putPublication(publication)

// And in the target Activity, in onCreate():
val publication = intent.getPublication(this)

// Don't forget to call this in Activity.onDestroy(), to release the Publication:
intent.destroyPublication()
```

### CODE REVIEW

File: r2-testapp/src/main/java/org/readium/r2/testapp/epub/EpubActivity.kt [hunk 1]
```diff
@@ -211,12 +210,13 @@ class EpubActivity : R2EpubActivity(), CoroutineScope, NavigatorDelegate/*, Visu
...
                 val locator = searchResult[position]
-                val intent = Intent()
-                intent.putExtra("publicationPath", publicationPath)
-                intent.putExtra("epubName", publicationFileName)
-                intent.putExtra("publication", publication)
-                intent.putExtra("bookId", bookId)
-                intent.putExtra("locator", locator)
+                val intent = Intent().apply {
+                    putPublicationFrom(intent)
+                    putExtra("publicationPath", publicationPath)
```
Comment (qnga) [inline r2-testapp/src/main/java/org/readium/r2/testapp/epub/EpubActivity.kt:215]: The name `intent` is a bit confusing here.

Comment (mickael-menu) [reply r2-testapp/src/main/java/org/readium/r2/testapp/epub/EpubActivity.kt:215]: @qnga Do you mean here `putPublicationFrom(intent)`? Yeah maybe we could pass the `Activity` instead.
